### ISSUE TITLE
SPM Failure

### ISSUE THREAD

**Issue by tooolbox** [johndpope/IO-swift#1]
I tried to add this to my project in Xcode using `File > Swift Packages > Add Package Dependency` and while it listed out the three tags `0.0.1` through `0.0.3` and let me pick from them, I got this message:

> The package dependency graph can not be resolved; unable find any available tag for the following requirements: https://github.com/johndpope/IO-swift.git — 0.0.3..<1.0.0

I'm not familiar with SPM particularly, so no idea why this is happening, but wanted to report it.

Thanks for helping make the Go I/O library available in Swift :)

**Comment by johndpope** [comment]
just try ripping out the code and embedding

**Comment by tooolbox** [comment]
Yeah, that did work fine.  Should I close this as wontfix?
